name: blockend_cli
description: A Dart package designed to streamline the development of robust blockchain applications.
version: 0.0.4
homepage:

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  args: ^2.4.2

executables:
  blockend: base
